#!/usr/bin/env python3
"""
Stage 00 — strip `phase` from every artefact and remove what we no longer need.

Idempotent: safe to run twice. Prints everything it does. Nothing is deleted
that can't be regenerated by build_dataset.py or a drafting run.

    python cleanup.py --dry-run     # see the plan
    python cleanup.py               # do it
"""
import argparse, json, os, shutil, sys

JSONL_WITH_GOLD = ["eval_candidates.jsonl", "eval_drafts.jsonl",
                   "eval_drafts_b.jsonl", "eval_gold.jsonl",
                   "eval_blind.jsonl", "sft_pool.jsonl"]

# One-shot diagnostics that produced the schema decisions. Not part of the
# pipeline any more, but they are the provenance for "why these four fields" —
# keep them out of the way rather than deleting them.
ARCHIVE = ["check_extractive.py", "inspect_misses.py"]

# Superseded or regenerable.
DELETE = ["review.py",            # adjudicate.py does this better
          "sample_docs.jsonl",    # scratch output of check_extractive
          "__pycache__"]

KEEP = ["ctg_common.py", "build_dataset.py", "draft_labels.py",
        "adjudicate.py", "test_stage00.py", "cleanup.py",
        "eval_candidates.jsonl", "eval_drafts.jsonl", "eval_drafts_b.jsonl",
        "eval_gold.jsonl", "eval_blind.jsonl",
        "sft_pool.jsonl", "cpt_corpus.jsonl", "manifest.json"]

def strip_phase_jsonl(path, dry):
    if not os.path.exists(path):
        return None
    rows, hits = [], 0
    with open(path) as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            g = r.get("gold")
            if isinstance(g, dict) and "phase" in g:
                del g["phase"]
                hits += 1
            rows.append(r)
    if hits and not dry:
        tmp = path + ".tmp"
        with open(tmp, "w") as f:
            for r in rows:
                f.write(json.dumps(r) + "\n")
        os.replace(tmp, path)
    return hits, len(rows)

def strip_phase_manifest(path, dry):
    if not os.path.exists(path):
        return None
    m = json.load(open(path))
    changed = False
    if "phase" in (m.get("schema_keys") or []):
        m["schema_keys"] = [k for k in m["schema_keys"] if k != "phase"]
        changed = True
    for split in (m.get("splits") or {}).values():
        nr = split.get("null_rate") or {}
        if "phase" in nr:
            del nr["phase"]
            changed = True
    if changed and not dry:
        json.dump(m, open(path, "w"), indent=2)
    return changed

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--dir", default=".")
    args = ap.parse_args()
    os.chdir(args.dir)
    dry = args.dry_run
    tag = "[dry-run] " if dry else ""

    print(f"{tag}working in {os.getcwd()}\n")

    print("--- stripping `phase` -------------------------------------------")
    for p in JSONL_WITH_GOLD:
        res = strip_phase_jsonl(p, dry)
        if res is None:
            print(f"  {p:<26} (absent)")
        else:
            hits, n = res
            print(f"  {p:<26} {hits}/{n} records had phase"
                  f"{'' if hits else '  — already clean'}")
    ch = strip_phase_manifest("manifest.json", dry)
    print(f"  {'manifest.json':<26}"
          + ("schema_keys + null_rate updated" if ch else
             "(absent)" if ch is None else "already clean"))

    print("\n--- archiving diagnostics ---------------------------------------")
    if not dry:
        os.makedirs("diagnostics", exist_ok=True)
    for f in ARCHIVE:
        if os.path.exists(f):
            print(f"  {f} -> diagnostics/{f}")
            if not dry:
                shutil.move(f, os.path.join("diagnostics", f))
        else:
            print(f"  {f:<26} (absent)")

    print("\n--- removing ----------------------------------------------------")
    for f in DELETE:
        if os.path.exists(f):
            print(f"  rm {f}")
            if not dry:
                shutil.rmtree(f) if os.path.isdir(f) else os.remove(f)
        else:
            print(f"  {f:<26} (absent)")

    print("\n--- anything else present ---------------------------------------")
    known = set(KEEP) | set(DELETE) | {"diagnostics"}
    extra = sorted(f for f in os.listdir(".") if f not in known)
    print("  " + (", ".join(extra) if extra else "(nothing unexpected)"))
    if extra:
        print("  ^ not touched — review these yourself")

    print("\n--- verifying ---------------------------------------------------")
    bad = 0
    for p in JSONL_WITH_GOLD:
        if not os.path.exists(p):
            continue
        for line in open(p):
            if line.strip() and "phase" in json.loads(line).get("gold", {}):
                bad += 1
    if os.path.exists("ctg_common.py"):
        import importlib.util
        spec = importlib.util.spec_from_file_location("cc", "ctg_common.py")
        m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
        print(f"  schema keys: {m.SCHEMA_KEYS}")
    print(f"  records still carrying phase: {bad}"
          + ("  <-- rerun without --dry-run" if bad and dry else ""))

if __name__ == "__main__":
    main()
